---
title: Post-Election Campaign Narrative
author: Ethan Kelly
date: '2022-12-07'
slug: post-election-campaign-narrative
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2022-12-07T14:38:13-08:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

Post-Election Campaign Narrative

Welcome to my post-election campaign narrative blog post! In this blog post, we will be exploring Maryland’s 6th Congressional District. After intense judicial drama dealing with the legislative district boundaries, Maryland’s 6th district became instantly one of the most competitive in the country. 

Let’s move into understanding the background of the 6th district! 

== Background == 

To begin, the 6th district is a relatively new one. It was birthed out of the 2020 congressional redistricting cycle & serves to be as the most important district within the state of Maryland. However, to understand the competitive nature of this district & the overall election results, it is important to understand how this district came to be so competitive. 

After Democrats expanded their supermajority in the State Legislature, the Maryland Democrats passed a congressional map that *intitally* saved the incumbent, David Trone, from any level of competitiveness for the next decade. According to FiveThirtyEight, a reputable source of political information, the 6th district was intended to be D+12 (the previous district was D+16). However, a Circuit Court Judge named Lynne Battaglia struck down the map, calling it “unconstitutional, and [that it] subeverts the will of those governed.” 

Consequently, the map had to be redrawn – fairly this time. Upon completion of the new map, Governor Larry Hogan signed it into law, and the district then held a partisan lean of R+1. From this moment onward, Maryland’s 6th district was on the GOP’s radar. With high expectations for the midterms, they thought this would be a prime opportunity for a pickup for Republicans. 

Before we get more into election forecasting, results, and analysis — we should know more about the 6th. In terms of demographics, of the estimated 790,000 residents, the district is majority-white, with about 56% of constituents identifying as White Americans. An additional 14% identify as Black, 16% as Hispanic, and 12% as Asian; about 3% remains two + more races (or other). This district is diverse – but is dominated by urbanites (+suburbanites, as there is no classifier for this), with 84% of the district being referred to as “urban” and 16% referred to as “rural.” In terms of median household income, the 6th district’s is $86,077, higher than the national median of $70,784. About 91% of the district has a high school diploma, with 43% having additionally graduated college. 
Now that we’ve talked demographics, let’s move directly into geography, candidates, and electoral history. In terms of geography, Maryland’s 6th district is one of Maryland’s largest. It contains semi-large cities in Maryland, alongside some extremely large plots of farmland. It is a combination of urban, suburban, and rural areas – with most of the land coming from urban + suburban areas. It is connected to West Virginia and Virginia, while also directly bordering Pennsylvania on the top. 

As for the candidates, incumbent Democrat David Trone ran for re-election in this district. He was first elected in 2018 during the blue-wave midterm, after Representative John Delaney announced his bid for President of the United States in 2017. Trone’s first time running for Congress was in 2016 (for an entirely different district), where he rose to prominence for spending $13 million of his own money on the race. However, he lost to John Delaney, but won the seat back 2 years later. He is a former winemaker & business, who’s stake in the district was mostly his incumbency. As a candidate, Trone was not regarded as extremely powerful, but was not thought of as “weak” or “lackluster.”

The Republican nominee, Neil Parrott, ran against Trone in the 2020 election. He was a recognized name who faced a well-known Republican opponent in the primary. His opponent, Matthew Foldi, was endorsed by Larry Hogan, Donald Trump Jr., Kevin McCarthy, and many more. However, Foldi ended up losing by over 50% to Neil Parrott – mostly due to Parrott’s previous candidacy & name recognition. Parrott fed into Donald Trump’s 2020 election lies & was involved in the “observation of ballot counting” in Pennslyvania.  

Now, let’s move into electoral history. Since we are working with a brand new congressional district, the past voting history is a bit difficult to use as a factor in understanding the district. However, we do have PVI’s based on how this new district would have voted in the past. Applying the new boundaries to the 2020 presidential election, Joe Biden won the 6th district by single digits (under 5%). Estimates have it around Biden +1-3%, quite insignificant from the former district’s 15%+ margin for President Biden. To aide in the understanding of the district, FiveThirtyEight rated it as R+1 & the Cook PVI has it as D+2. 

Finally, as my forecast was rooted in expert predictions, we will be looking at expert forecasts for this election. My 3 main forecasters for my model came from the Cook Political Report, Inside Elections, and Larry Sabato’s Crystal Ball. Their rating were as follows (in respective order): Likely Democrat, Likely Democrat, and Lean Democrat. Altogether, they average to a semi-significant Democratic victory. 

Since we know a lot about the district, let’s move directly into the results vs. the forecast.

== Accuracy of Forecasts == 

My forecast was rooted in the predictions of expert forecasters. As previously mentioned, I worked with Larry Sabato’s Crystal Ball, Inside Elections, and the Cook Political Report. My forecast used accuracy of the previous forecasts from 2012-2020 in order to create a model to predict each district in 2022. In this case, my model predicted that incumbent David Trone would win 63.7% of the vote in the 2022 election. The final result ended up being about 9 points worse for Democrats, with Trone winning 54.8% of the vote. 

Most pundits expected David Trone to win his race, as nearly all of the forecast websites and companies predicted a Democratic hold. The closest it was expected to be was a “Toss-Up” declaration. FiveThirtyEight’s 2022 House Model predicted David Trone to win about 52% of the vote, giving him a 71% chance of winning. FiveThirtyEight uses expert forecasters in a similar fashion to my model — expect they add it into a number of other factors. 

Reflecting on my prediction, I significantly overestimated Democratic support. Regardless of the year, the 6th district likely will not be going to a Democrat with 63%. David Trone’s result was surprising, in terms of margin at least, and while my model did predict a significant margin, it was still off. 

Altogether, the model I put together was accurate in the overall winner & accurate in suggesting a larger-than-average victory. However, there was consistent overestimation for Democrats (across the country, not just here) in my model. My final prediction was 220-215, Democrats winning the majority. My final model ended up being wrong (in terms of predicted party victory) by 17 seats in total, mostly inaccurate calls for Democrats.

Now that we’ve seen the accuracy, or lack thereof, of my model, it is time to move into the narrative of the campaign. 

== Campaign Narrative == 

This campaign, like many others, was nationalized to an extremely high extent. Both candidates were associating each other with top names, such as Donald Trump and Joe Biden. Trone and Parrott aimed to make this race beyond themselves — largely in part that neither of them were super well-received or admired. 

On the side of the David Trone, his campaign focused on a multitude of issue leading into the summer of 2022. Whether it was focused on COVID-19 recovery, mental health, etc., Trone was the stereotypical Democrat aiming to highlight their victories over the past 2 years. However, when Roe V. Wade was overturned in June of 2022, Trone’s campaign shifted primarily to the issue of abortion. 

In context, Maryland is an extremely pro-choice state. Opinions on being pro-abortion-rights are significantly high, being significantly higher than Democratic Party vote share on the statewide level. As a result, a competitive, R+1 district, such as the 6th, will be likely in favor of abortion access by a margin of 60-40. Point being: Trone’s campaign shifted to an issue they knew they would be the Republicans on.

== Campaign + Media Narrative == 

The media’s narrative was pretty similar to that on the national level. This district was seen as one of the bigger victories (should it had happened) for the GOP — as it would be flipped “deep blue Maryland.” The narrative was that the voters in the 6th were pushing back on President Biden & wished to express their discontent with the Democratic Agenda. 

The presence of this race in local media was pretty significant — outmatching any other congressional district in the state. The media covered Trone’s focus on abortion, highlighting some of the comments made by his opponent. As the country turned to abortion, so did the Maryland press. Additionally, the coverage was hyping up the competitiveness of this district, likely to an over exaggerated extent. The district was going to be close, but it was not a nail-biter nor was it going to determine the balance of power in the House. 

The Bethesda, Maryland magazine: the Bethesda Beat, highlighted the competitive nature of the race right before the election. In a late-October article, they claimed the race was “heating up in the final days,” referencing insider polls that showed the race within a few points. They continued this article with a showcase of some of Parrott’s ads against Trone, which could very well summarize the GOP’s main points by the end of the race. The advertisement was as follows: “Fire far-left David Trone… We can’t afford another two years of the Biden/Pelosi/Trone agenda.” Essentially — tying Trone to Pelosi & Biden was the biggest attack the Republicans had. By this point, one can assume that the race was moving away from the GOP if THIS was their hard-hitter.

Additionally, local drew significant juxtapositions between Trone and Parrott. Parrott told the local media that he would be “definitely interested in joining [the House Freedom Caucus],” a caucus responsible for Marjorie Taylor Greene, Lauren Boebert, and 38 other far-right Republicans in the House. This comment stuck with the media & the voters. Non-local sites such as OpenSecrets, the Diamondback, and the Washington Post dove deeper into policy differences between the candidates. Whether on issues of social security, military spending, healthcare, etc. — this was not the concern of voters & thus barely covered by the media. 

From the side of Neil Parrott, the media covered him with heavy scrutiny. His comments about election denial & the insurrection were covered quite heavily. Additionally, he made a comment that people with HIV should not be able to get a tattoo, and another comment about banning abortion in every case. These comments Parrott made resulted in extensive coverage of his gaffes and mistakes. Unlike Trone, Parrott is extremely outspoken on social issues that the 6th district does not align with him on. As a result, he likely lost voters on the key issues that Trone highlighted. 

In terms of endorsements after the primary elections, they typically do not hold much weight. Both sides of the aisle send in big names to endorse their lesser-known candidates. However, there was little media coverage of Parrott’s Republican endorsements.. because he had so few. After the primary, the majority of Republicans who endorsed Matthew Foldi refused to endorse Parrott in the general election. Whether through ignorance or explicitly stating as such, top Republicans such as Larry Hogan did not back Parrott in the general.

His comments on abortion, the election, and much more likely shifted voters away from him. While I do not personally think voters viewed Trone as an aweinspirational candidate, he was certainly higher in “candidate quality” than Parrott. He aligned with voters on more issues and he knew how to play the political game. Unfortunately for Parrott, it was evident that Trone was the better candidate — and it came across through the reporting of the media. Essentially, Parrott dug his own grave (with help of national Republicans & the United States Supreme Court). 

In specifics, Parrott made a number of missteps that can be quantified into points below:
His candidacy was rooted in tying Trone to Biden – despite the expectations for 2022, the year ended up being a lot more about candidate quality than we thought. While President Biden’s shortcomings were centerfocused in some regard, they were not the main focus of the election & Parrott failed to recognize this. 
He treated this race as a Trump-like figure – in his case, Parrott very much was an extreme Republican given the sentiment across the district. Rather than be a swing-district Republican, he was quite more conservative than other Republicans who did phenomenally here. Governor Larry Hogan, a Republican, won MD-6 by over 10 points – yet Parrott lost here by 10 points. Why? GOP candidate quality & stances. 
He gave the media too much to work with – going on the record with points that can be viewed as anti-Women, anti-LGBTQ, etc. are things that a candidate should avoid. For Parrott, he was loud & proud and did not avoid the press with these topics. He failed to pivot & shift focus correctly & the voters knew this. 

The candidates did a lot in terms of campaigning. Both utilized social media as a major fundraising tool, while they crowded the airwaves with TV ads day-after-day. There was extensive ground game by the Maryland Democrats & Republicans, as all eyes were focused on this race. Without a competitive race in the state, it was all hands on deck. Even some Virginia Democrats came up to canvass for David Trone. The point is: this campaign was the hottest issue in all of Maryland and it showed.

== What does Election Analytics tell us? == 

According to Brown (2014), incumbency is a factor that Trone likely did not ride to re-election. With the economy moving in an unsatisfactory direction, Trone likely should have been punished for this. Biden’ s inability to do major initiatives related to inflation & other aspects of the economy likely hindered Trone’s victory. However, in relation to incumbency, voters do not always have a preference on that basis alone. A lot of other factors are thrown into it, but I do not know if I entirely agree with the literature, however it is clear (in reflection) that Trone likely won due to many other factors.

However, to the point of other factors influencing the race, Trone was still associated with President Biden. According to FiveThirtyEight, he voted with President Biden 100% of the time since getting into office. As mentioned in Canes-Wrote et al. (2020), there are electoral ramifications for voting with your party. Especially in a swing district, vote share has been found to decrease as an incumbent’s support for their own party increases. However, while Trone did not win by 20 (as he did in 2018), he severely outperformed the expectations for this district.

As we look to reflect upon this race, it is important to look at literature that deals with reflecting on models & accuracy of predictions. We know from Vavreck (2009) that candidates that deal with economic fallback (aka Trone) must shift the race to a focus on issues beyond the economy. Ultimately, Trone did this successfully. As acknowledged by Vavreck, candidates do not always have the ability to do this. Looking at candidates in 2010 & 2014 – it was difficult to separate the economy from the voters. However, in 2022, the Supreme Court’s intervention in a woman’s right to chose resulted in candidates, like Trone, the ability and agency to shift the focus on abortion (and other issues impacted by the SCOTUS). 

== Conclusion == 

In conclusion, the Maryland 6th Congressional District race was more competitive than it had been in nearly a decade. The district, redrawn out of a fresh redistributing cycle, was the focus of media outlets across Maryland and the nation. Two candidates ran: incumbent Democrat David Trone & State Senator Neil Parrott. Parrott ran against Trone in the past, but faced new scandals and challenges as he headed into this election. Trone, on the other hand, shifted his campaign focus to the issue of abortion — a move inspired by the Supreme Court’s decision to overturn Roe V Wade. 

My forecast was based on the 3 main sources: Cook, Inside, and the Crystal Ball. Together, my model predicted Democrats winning the 6th district with 63% of the vote. They ended up winning 54% — an overestimation on my end of 9%. This district is a Biden +1-3% district & has a 538 PVI of R+1. Candidate quality played a major role in the Democratic Party’s victory — despite neither candidate being extremely strong, Parrott’s weakness was very apparent.

Thank you for taking the time to read this post! Following this race over the Fall Semester was very fun :)
 
Till we meet again,
Ethan <3

Direct Bibliography (many other sources went into research over the semester): 

Brown, Adam R. “Voters Don't Care Much About Incumbency.” Journal of Experimental Political Science, vol. 1, no. 2, 2014, pp. 132–43, https://doi.org/10.1017/xps.2014.6.

Canes-Wrone, Brady, D. W., & Cogan, J. F. (2002). Out of Step, Out of Office: Electoral Accountability and House Members' Voting. The American Political Science Review, 96(1), 127–140. https://doi.org/10.1017/S0003055402004276

Vavreck, Lynn, and Lynn Vavreck. “The Message Matters.” 2009. 232 Pp, STU - Student edition, Princeton University Press, 2009, pp. 1–205, https://doi.org/10.1515/9781400830480.

Peck, Louis. “Trone vs. Parrott Rematch Heats up in Final Days before Nov. 8 Election.” Bethesda Magazine & Bethesda Beat, Bethesda Magazine & Bethesda Beat, 27 Oct. 2022, bethesdamagazine.com/2022/10/27/trone-vs-parrott-rematch-heats-up-in-final-days-before-nov-8-election/. Accessed 17 Dec. 2022. ‌

Board, Editorial. “The Post Endorses Trone and Parrott in the Maryland 6th District Primaries.” Washington Post, The Washington Post, 10 July 2022, www.washingtonpost.com/opinions/2022/07/10/maryland-6th-district-primary-endorsement-2022/. Accessed 17 Dec. 2022. ‌

“Redistricting Brings New Competition to Maryland’s 6th Congressional District.” The Diamondback, 19 Oct. 2022, dbknews.com/2022/10/19/district-6-maryland-congressional-election-redistricting/. Accessed 17 Dec. 2022. ‌

Siemons, Jorja. “GOP Lead Fundraiser Neil Parrott Wins Maryland Primary in Competitive District.” OpenSecrets News, 22 July 2022, www.opensecrets.org/news/2022/07/leading-gop-fundraiser-neil-parrott-wins-primary-in-marylands-6th-district/. Accessed 17 Dec. 2022. ‌

