---
title: 'Blog Post #7'
author: Ethan Kelly
date: '2022-10-25'
slug: blog-post-7
categories: []
tags: []
subtitle: ''
summary: ''
authors: []
lastmod: '2022-10-25T22:01:15-04:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---



<p>== Final Blog Post Before Midterm Prediction ==</p>
<p>This blog post will be the final one held before the Midterm Elections. We are in quite an exciting time as we enter into November 2022 – my next blog post will ultimately be my final prediction. As it stands currently, the Democrats are losing on the national popular vote (FiveThirtyEight + RealClearPolitics polls), they are losing in expert forecasts (in the House + nearly in the Senate), and this blog post will be focused on one thing: updating my 2022 model.</p>
<p>This week’s blog extension gave the opportunity to work on updating my statistical model – and thus, I wanted to use this opportunity to predict the 2022 House Elections given the 2018 midterm elections. Previously, I had explored the accuracy of the 2018 midterms as it pertained to predictions from 2018 (I used the data to predict itself), but now, we will be moving up a level.</p>
<p>To begin, we will start by modeling the accuracy of the 2018 &amp; 2020 expert predictions + 2018 &amp; 2020 results!</p>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="{{< blogdown/postref >}}index.en_files/figure-html/unnamed-chunk-5-1.png" width="672" />
What we find here is that there seems to be a clear, visual, correlation between the rating &amp; the Democratic Party’s vote share. The Democrats do significantly better when the rating is around 1, which checks out, and significantly worse when the rating is around 7, which also makes sense. Altogether, we find that this usage of comparing rating vs. Democratic Party vote share should work as a predictor for the 2022 midterms.</p>
<p>Now, we are going to include the 2022 midterm elections, in which the model will not be utilizing a pooled model – this is strictly based on the 2018 &amp; 2020 expert ratings + final results. In our predictive model, we will only be provided with the expert ratings for each individual house district. We are pivoting to a prediction for the midterms given the extremely close nature of the November elections. This will tremendously help in figuring out my final prediction.</p>
<p>Now, let’s move into predicting the 2022 midterms based on the 2018, 2020 election results.</p>
<p>== 2022 Prediction ==</p>
<pre><code>##        group value
## 1 Republican   212
## 2   Democrat   223</code></pre>
<p><img src="{{< blogdown/postref >}}index.en_files/figure-html/unnamed-chunk-7-1.png" width="672" />
As you can see above, the 2022 prediction based on the 2018/2020 expert predictions accuracy gives the Democratic Party 223 seats, to the Republican Party’s 212. This would be a tremendous over performance for national Democrats, allowing them to EXPAND their House majority, relative to where it is today. This has rarely ever happened in the past 40 years, where typically incumbent parties LOSE control of one or both chambers in the U.S. Congress.</p>
<p>== Copy Paste in from Google Docs ==</p>
